#!/usr/bin/env bash
#Best school 10x 9th hi
counter=1
while ((counter<=10))
do
	echo "Best School"
	if ((counter==9)); then
		echo "Hi"
	fi
	((counter++))

done
© 2022 GitHub, Inc.
Terms
Privacy
Security
